main: me.lebobus.servercore.Main
name: nodepvp
version: '1.0'
description: Core plugin of nodepvp.
author: Bobus
commands:
     ban:
      description: Ban players.
      usage: /ban [player]
     unban:
      description: Unban players.
      usage: /unban [player]
     kick:
      description: Kick players.
      usage: /kick [player]
     mute:
      description: Mute players.
      usage: /mute [player]
     unmute:
      description: Unmute players.
      usage: /unmute [player]
     nodepvpcore55x2:
      description: Open 55x2 GUI.
      usage: /nodepvpcore55x2